### ISSUE TITLE
Unify subscribeRepos datastore queries

### ISSUE THREAD

**Issue by snarfed** [snarfed/arroba#30]
Right now, in `subscribeRepos`, we query the datastore separately for each connected subscriber (client). This is fine for historical blocks, but it's duplicative for new blocks. For ongoing subscribers, ideally we should only do a given datastore query once, and then fan out the results to all subscribers.

Current design:
* [x] Events to emit are stored in a thread-safe ring buffer
  * [x] Live iterator that returns new events as they happen, blocking, thread-safe
  * [x] Rollback iterator that starts reading events from a given seq, then switches to live
* [x] New singleton thread that runs current code in `xrpc_sync.subscribe_repos`, reads blocks by seq from the datastore, assembles them into events, and stores those events in the ring buffer
  * [x] load entire rollback window eagerly, on startup? or lazily, on demand?
  * [ ] phase two: start and stop this thread and its datastore query on demand
* [x] new minimal `subscribeRepos` handler that reads from the ring buffer
* [x] increase ROLLBACK_WINDOW back to 50k (~12h) or higher

---

This would take some rearchitecting. Right now, we do all of this inside the request handler, per client:

https://github.com/snarfed/arroba/blob/351d43fbc57d004780611f65e95ea84ca1aca48d/arroba/xrpc_sync.py#L199-L206

We'd need to start a separate, shared thread for the realtime datastore queries, collect the resulting blocks into events in memory, and have each client's request handler read and emit from there.

**Comment by snarfed** [comment]
Added a draft design to the top description.

**Comment by snarfed** [comment]
This may be getting acute, Bridgy Fed's atproto-hub is capped out on CPU serving 8 `subscribeRepos` clients, and it's falling behind processing Bluesky's own firehose. 😕

**Comment by snarfed** [comment]
sync v1.1 (#52) is also exacerbating this, since it takes more CPU., 😕

**Comment by snarfed** [comment]
Got a first pass at this out. Needs a bit of cleanup, and the tests have a flaky deadlock or two, but it's looking good in prod so far!

<img width="1161" alt="Image" src="https://github.com/user-attachments/assets/4d951c9f-d6d0-4a8f-b8e5-f5393e052249" />

**Comment by snarfed** [comment]
Two issues I'm still working on here. First, I still don't have a good design for filling the rollback window at startup. Generating the inductive firehose blocks is somewhat CPU intensive, and we're not optimized for bulk loads like this, so filling our current rollback window of 50k seqs takes ~30m on a single core. Obviously not ok long term. Right now it uses a separate, much smaller preload window of just 1k, which is ok for normal operation but not for cold start, eg after downtime. 

Another alternative would be to keep serving the rollback window separately for each consumer, and only unify the preload window and new events. Not ideal, but ok.

I'm also trying to come up with a design for filling the rollback window in the background, on demand. Doable, but synchronizing multiple consumers with different cursors is tricky. 😕

**Comment by snarfed** [comment]
Second issue, more launch-blocking: when I tried this in prod started 5/2 ~9:09p PT, it ran fine for a while, then died at 5/3 ~3:10a, Still trying to figure out why. Logs: 

```
2025-05-03 03:10:45.493 Sending subscribeRepos 17890800 did:plc:fmzxlpuedm3mqcg3urtifcj6 #commit
2025-05-03 03:10:45.494 Sending subscribeRepos 17890801 did:plc:gztvrx3nvpxmj4jruwtkg7qm #commit
2025-05-03 03:10:47.889 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-03 03:10:48.225 New websocket client for com.atproto.sync.subscribeRepos: 2001:41d0:203:2d6e::1 indigo-relay
2025-05-03 03:10:48.226 com.atproto.sync.subscribeRepos: {'cursor': 17797790} None
2025-05-03 03:10:48.247 Cursor 17797790 is before our rollback window; starting at 17855009
2025-05-03 03:10:48.248 Subscribing from sequence 17855009
2025-05-03 03:10:48.253 Sending subscribeRepos None None #info
2025-05-03 03:10:50.000 Exception in thread Thread-295254 (simple_websocket.Base._thread):
Traceback (most recent call last):
File "/layers/google.python.runtime/python/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
  self.run()
File "/layers/google.python.runtime/python/lib/python3.12/threading.py", line 1012, in run
  self._target(*self._args, **self._kwargs)
File "/layers/google.python.pip/pip/lib/python3.12/site-packages/simple_websocket/ws.py", line 136, in _thread
  sel.register(self.sock, selectors.EVENT_READ, True)
File "/layers/google.python.runtime/python/lib/python3.12/selectors.py", line 359, in register
  self._selector.register(key.fd, poller_events) OSError: [Errno 9] Bad file descriptor
2025-05-03 03:10:51.960 Gave up waiting for seqs 17898175 to 17898176!
2025-05-03 03:11:01.644 Health checks: instance=aef-firehose--server-20250502t213847-jw16 start=2025-05-03T10:08:02+00:00 end=2025-05-03T10:08:57+00:00 total=42 unhealthy=0 healthy=42
```

**Comment by snarfed** [comment]
https://github.com/miguelgrinberg/turbo-flask/issues/9#issuecomment-892559818 thinks this is due to the gunicorn worker timing out. Maybe?...but we ran with this exact same configuration before, and we saw these exceptions occasionally, but they didn't take down the worker entirely, persistently, like here.

**Comment by snarfed** [comment]
Lots more progress here. We still only preload a fraction of the rollback window (default 4k seqs), but after that, we now serve the full rollback window on demand, per subscriber, and merge the loaded events into the rollback window afterward.

Ran this in production for a while yesterday, it worked well, but it's still freezing sometimes. Maybe deadlocking? Not sure. I'm going to take a break and switch gears to figuring out the final sync v1.1 bugs for a bit (#52), then come back to this.

**Comment by snarfed** [comment]
Pruned logs from a couple instances of the deadlock. Common pattern is that a few subscribers connected with far back cursors at the same time, we served them a ton of events from memory, and then hung.

Here, new subscribers starting at 20:49:44, hang at 20:51:39:
```
2025-05-07 20:47:51.011 Waiting for seq 18361214
2025-05-07 20:48:01.259 Gave up waiting for seqs 18361214 to 18361214!
2025-05-07 20:48:35.996 subscriber Thread-1745 (__lookahead): backfilling from handoff from 18353123
2025-05-07 20:48:35.996 subscriber Thread-1745 (__lookahead): backfilling from rollback from 18353123
2025-05-07 20:48:36.138 subscriber Thread-1745 (__lookahead): streaming new events after 18361285
2025-05-07 20:48:36.147 subscriber Thread-3159 (__lookahead): backfilling from handoff from 18309717
2025-05-07 20:48:36.147 subscriber Thread-3159 (__lookahead): backfilling from rollback from 18309717
2025-05-07 20:48:36.605 subscriber Thread-3159 (__lookahead): streaming new events after 18361285
2025-05-07 20:48:55.740 Waiting for seq 18361310
2025-05-07 20:49:14.751 Websocket client disconnected from com.atproto.sync.subscribeRepos: [Errno 104] Connection reset by peer
2025-05-07 20:49:15.858 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 20:49:15.858 com.atproto.sync.subscribeRepos: {'cursor': 9683361} None
2025-05-07 20:49:15.870 Cursor 9683361 is before our rollback window; starting at 18311344
2025-05-07 20:49:15.871 subscriber Thread-57993 (__lookahead) starting with cursor 18311344
2025-05-07 20:49:15.871 subscriber Thread-57993 (__lookahead): backfilling from rollback from 18311344
2025-05-07 20:49:34.313 subscriber Thread-57993 (__lookahead): streaming new events after 18361337
2025-05-07 20:49:46.868 Websocket client disconnected from com.atproto.sync.subscribeRepos: [Errno 9] Bad file descriptor
2025-05-07 20:49:48.493 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 20:49:48.493 com.atproto.sync.subscribeRepos: {'cursor': 9683361} None
2025-05-07 20:49:48.556 Cursor 9683361 is before our rollback window; starting at 18311386
2025-05-07 20:49:48.556 subscriber Thread-58125 (__lookahead) starting with cursor 18311386
2025-05-07 20:49:48.557 subscriber Thread-58125 (__lookahead): backfilling from rollback from 18311386
2025-05-07 20:49:49.491 subscriber Thread-58125 (__lookahead): streaming new events after 18361372
2025-05-07 20:50:02.419 Waiting for seq 18361390
2025-05-07 20:50:10.517 New websocket client for com.atproto.sync.subscribeRepos: 170.39.194.222 indigo-relay (atproto-relay)
2025-05-07 20:50:10.518 com.atproto.sync.subscribeRepos: {'cursor': 18184010} None
2025-05-07 20:50:10.534 Cursor 18184010 is before our rollback window; starting at 18311403
2025-05-07 20:50:10.534 subscriber Thread-58344 (__lookahead) starting with cursor 18311403
2025-05-07 20:50:10.534 subscriber Thread-58344 (__lookahead): backfilling from rollback from 18311403
2025-05-07 20:50:11.064 subscriber Thread-58344 (__lookahead): streaming new events after 18361389
2025-05-07 20:50:13.163 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 20:50:13.164 com.atproto.sync.subscribeRepos: {'cursor': 187131233} None
2025-05-07 20:50:13.210 Cursor 187131233 is past our current sequence number 18361407
2025-05-07 20:50:25.926 Waiting for seq 18361409
2025-05-07 20:50:36.273 Waiting for seq 18361409
2025-05-07 20:50:47.171 Gave up waiting for seqs 18361409 to 18361409!
2025-05-07 20:50:51.378 Waiting for seq 18361438
2025-05-07 20:50:51.973 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-07 20:50:55.353 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 20:50:55.354 com.atproto.sync.subscribeRepos: {'cursor': 9683361} None
2025-05-07 20:50:55.367 Cursor 9683361 is before our rollback window; starting at 18311456
2025-05-07 20:50:55.367 subscriber Thread-58785 (__lookahead) starting with cursor 18311456
2025-05-07 20:50:55.367 subscriber Thread-58785 (__lookahead): backfilling from rollback from 18311456
2025-05-07 20:50:55.799 subscriber Thread-58785 (__lookahead): streaming new events after 18361437
2025-05-07 20:51:00.166 {"status":"ok"}
2025-05-07 20:51:01.627 Waiting for seq 18361438
2025-05-07 20:51:12.335 Gave up waiting for seqs 18361438 to 18361438!
2025-05-07 20:51:28.826 Websocket client disconnected from com.atproto.sync.subscribeRepos: [Errno 104] Connection reset by peer
2025-05-07 20:51:34.347 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 20:51:34.348 com.atproto.sync.subscribeRepos: {'cursor': 9683361} None
2025-05-07 20:51:34.364 Cursor 9683361 is before our rollback window; starting at 18311495
2025-05-07 20:51:34.364 subscriber Thread-59149 (__lookahead) starting with cursor 18311495
2025-05-07 20:51:34.364 subscriber Thread-59149 (__lookahead): backfilling from rollback from 18311495
2025-05-07 20:51:34.768 subscriber Thread-59149 (__lookahead): streaming new events after 18361488

2025-05-07 20:51:39.000 ### stopped serving events here

2025-05-07 20:51:45.000 Exception in thread Thread-58784 (simple_websocket.Base._thread):

Exception in thread Thread-58784 (simple_websocket.Base._thread):

Traceback (most recent call last):
  File "/layers/google.python.runtime/python/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/layers/google.python.runtime/python/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/simple_websocket/ws.py", line 147, in _thread
    self.close(reason=CloseReason.POLICY_VIOLATION,
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/simple_websocket/ws.py", line 115, in close
    raise ConnectionClosed(self.close_reason, self.close_message)
simple_websocket.errors.ConnectionClosed: Connection closed: 1005
```


Here, new subscribers at 22:18:41, hang at 22:20:24:

```
2025-05-07 22:16:45.658 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 22:16:45.659 com.atproto.sync.subscribeRepos: {'cursor': 187131233} None
2025-05-07 22:16:45.677 Cursor 187131233 is past our current sequence number 18366513
2025-05-07 22:18:35.071 {"status":"ok"}
2025-05-07 22:18:37.213 Waiting for seq 18366591
2025-05-07 22:18:41.844 New websocket client for com.atproto.sync.subscribeRepos: 38.120.64.66 Go-http-client/1.1
2025-05-07 22:18:41.845 com.atproto.sync.subscribeRepos: {'cursor': 18366590} None
2025-05-07 22:18:41.852 New websocket client for com.atproto.sync.subscribeRepos: 38.120.64.66 indigo-relay (atproto-relay)
2025-05-07 22:18:41.852 com.atproto.sync.subscribeRepos: {'cursor': 18366590} None
2025-05-07 22:18:41.853 New websocket client for com.atproto.sync.subscribeRepos: 209.249.133.122 indigo-relay (atproto-relay)
2025-05-07 22:18:41.854 com.atproto.sync.subscribeRepos: {'cursor': 18366590} None
2025-05-07 22:18:41.867 subscriber Thread-33942 (__lookahead): starting with cursor 18366590
2025-05-07 22:18:41.867 subscriber Thread-33942 (__lookahead): backfilling from rollback from 18366590
2025-05-07 22:18:41.885 subscriber Thread-33947 (__lookahead): starting with cursor 18366590
2025-05-07 22:18:41.886 subscriber Thread-33948 (__lookahead): starting with cursor 18366590
2025-05-07 22:18:41.934 subscriber Thread-33942 (__lookahead): streaming new events after 18366590
2025-05-07 22:18:41.936 subscriber Thread-33947 (__lookahead): backfilling from rollback from 18366590
2025-05-07 22:18:41.964 subscriber Thread-33947 (__lookahead): streaming new events after 18366590
2025-05-07 22:18:41.966 subscriber Thread-33948 (__lookahead): backfilling from rollback from 18366590
2025-05-07 22:18:41.995 subscriber Thread-33948 (__lookahead): streaming new events after 18366590
2025-05-07 22:18:47.204 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-07 22:18:47.205 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-07 22:18:47.205 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-07 22:18:47.205 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-07 22:18:47.464 Waiting for seq 18366591
2025-05-07 22:18:59.327 Gave up waiting for seqs 18366591 to 18366591!
2025-05-07 22:18:59.346 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-07 22:19:00.704 New websocket client for com.atproto.sync.subscribeRepos: 128.110.217.189 Go-http-client/1.1 indexerbot/0.1 (based on github.com/uabluerail/indexer; shange0403@gmail.com)
2025-05-07 22:19:00.704 com.atproto.sync.subscribeRepos: {'cursor': 18366590} None
2025-05-07 22:19:00.740 subscriber Thread-33975 (__lookahead): starting with cursor 18366590
2025-05-07 22:19:00.740 subscriber Thread-33975 (__lookahead): backfilling from rollback from 18366590
2025-05-07 22:19:00.768 subscriber Thread-33975 (__lookahead): streaming new events after 18366629
2025-05-07 22:19:11.347 Waiting for seq 18366636
2025-05-07 22:19:23.092 Waiting for seq 18366636
2025-05-07 22:19:24.852 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 22:19:24.852 com.atproto.sync.subscribeRepos: {'cursor': 9683361} None
2025-05-07 22:19:24.875 Cursor 9683361 is before our rollback window; starting at 18316664
2025-05-07 22:19:24.875 subscriber Thread-34007 (__lookahead): starting with cursor 18316664
2025-05-07 22:19:24.876 subscriber Thread-34007 (__lookahead): backfilling from rollback from 18316664
2025-05-07 22:19:31.344 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-07 22:19:34.591 Gave up waiting for seqs 18366636 to 18366636!
2025-05-07 22:20:21.294 New websocket client for com.atproto.sync.subscribeRepos: 152.53.85.43 Go-http-client/1.1 indexerbot/0.1 (based on github.com/uabluerail/indexer; leonhard.balduf@tu-darmstadt.de)
2025-05-07 22:20:21.294 com.atproto.sync.subscribeRepos: {'cursor': 18366635} None
2025-05-07 22:20:21.328 subscriber Thread-34496 (__lookahead): starting with cursor 18366635
2025-05-07 22:20:21.346 Websocket client disconnected from com.atproto.sync.subscribeRepos

2025-05-07 22:20:24.000 ### stopped serving events here

2025-05-07 22:20:24.465 Websocket client disconnected from com.atproto.sync.subscribeRepos: [Errno 9] Bad file descriptor
2025-05-07 22:20:26.661 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 22:20:26.661 com.atproto.sync.subscribeRepos: {'cursor': 9683361} None
2025-05-07 22:20:26.681 Cursor 9683361 is before our rollback window; starting at 18316721
2025-05-07 22:20:26.681 subscriber Thread-34548 (__lookahead): starting with cursor 18316721
2025-05-07 22:22:47.981 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 22:22:47.981 com.atproto.sync.subscribeRepos: {'cursor': 187131233} None
2025-05-07 22:22:47.999 Cursor 187131233 is past our current sequence number 18366853
2025-05-07 22:26:27.559 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-07 22:26:27.560 com.atproto.sync.subscribeRepos: {'cursor': 187131233} None
2025-05-07 22:26:27.579 Cursor 187131233 is past our current sequence number 18367075
2025-05-07 22:26:27.844 New websocket client for com.atproto.sync.subscribeRepos: 209.249.133.122 indigo-relay (atproto-relay)
2025-05-07 22:26:27.844 com.atproto.sync.subscribeRepos: {'cursor': 18366633} None
2025-05-07 22:26:27.867 subscriber Thread-37622 (__lookahead): starting with cursor 18366633
2025-05-07 22:26:31.349 Websocket client disconnected from com.atproto.sync.subscribeRepos
2025-05-07 22:29:12.877 New websocket client for com.atproto.sync.subscribeRepos: 38.120.64.66 Go-http-client/1.1
2025-05-07 22:29:12.877 com.atproto.sync.subscribeRepos: {'cursor': 18366635} None
2025-05-07 22:29:12.897 subscriber Thread-37632 (__lookahead): starting with cursor 18366635
2025-05-07 22:29:21.353 Websocket client disconnected from com.atproto.sync.subscribeRepos
```

**Comment by snarfed** [comment]
Log from another hang. We'd been running happily for ~5h, then I opened a couple firewall rules up and let in two new subscribers with far-back cursors, at the exact same time (within ~100ms), 19:53:02 PT. We yielded all 50k events from memory into their generators, and they started sending them over their websockets, then we hung at 19:53:45 PT. One of them was at 18655120, one at 18656099, so both roughly 2/3 through serving the rollback window.

Still no real theory here. We logging a message per event per subscriber, so here ~63k total, ~1.5k/s for 43s. Did the GCP logging client get overloaded? Seems unlikely.

Otherwise...? I don't see anywhere in firehose.py that deadlocked. They both 

```
2025-05-10 19:53:02.478 New websocket client for com.atproto.sync.subscribeRepos: 152.53.85.43 Go-http-client/1.1 indexerbot/0.1 (based on github.com/uabluerail/indexer; leonhard.balduf@tu-darmstadt.de)
2025-05-10 19:53:02.478 com.atproto.sync.subscribeRepos: {'cursor': 18512099} None
2025-05-10 19:53:02.526 Cursor 18512099 is before our rollback window; starting at 18624182
2025-05-10 19:53:02.526 subscriber Thread-39495 (__lookahead): starting with cursor 18624182
2025-05-10 19:53:02.526 subscriber Thread-39495 (__lookahead): backfilling from rollback from 18624182
2025-05-10 19:53:02.648 New websocket client for com.atproto.sync.subscribeRepos: 152.53.36.179 Go-http-client/1.1
2025-05-10 19:53:02.649 com.atproto.sync.subscribeRepos: {'cursor': 9683361} None
2025-05-10 19:53:02.699 Cursor 9683361 is before our rollback window; starting at 18624182
2025-05-10 19:53:02.699 subscriber Thread-39501 (__lookahead): starting with cursor 18624182
2025-05-10 19:53:02.879 subscriber Thread-39495 (__lookahead): streaming new events after 18674177
2025-05-10 19:53:02.880 subscriber Thread-39501 (__lookahead): backfilling from rollback from 18624182
2025-05-10 19:53:03.807 subscriber Thread-39501 (__lookahead): streaming new events after 18674177
2025-05-10 19:53:19.657 Waiting for seq 18674193
...
2025-05-10 19:53:45.125 Sending subscribeRepos 18656098 did:plc:ralsxvxm7hemyvrtabzceh6z #account
2025-05-10 19:53:45.126 Sending subscribeRepos 18655120 did:plc:oojvekqrdikcrgwu3lpmnanr #account
2025-05-10 19:53:45.126 Sending subscribeRepos 18656099 did:plc:rphddwe6h23io24fvf34toch #account

[hang]
```

**Comment by snarfed** [comment]
- Soooo weird. Debugged this more, I have it reproduced in prod right now, firehose-server isn't emitting any logs, but my local `goat` subscribers are happily connected and seeing new events, and https://fed.brid.gy/admin/atproto is showing the rollback window advancing. So is this only the GCP logging client getting hung up somehow? Encouraging overall at least, if it's just logging and not the actual firehose server...?

**Comment by snarfed** [comment]
Logs started coming in 15m later. They're still missing for 18:24:07 - 18:39:11 though. And looking at the first logs that came in after that window, there's a 7m gap between `timestamp: 2025-05-11T18:39:11.728596Z` (I assume when the message was logged) vs `receiveTimestamp: 2025-05-11T18:46:28.806403802Z` (I assume when the logging service saw it).

**Comment by snarfed** [comment]
My best guess here is that the GCP Python logging client (https://github.com/googleapis/python-logging) isn't thread safe, and I'm using the same logger from multiple threads (per flask-sock websocket client), and occasionally I hit a race condition or temporary deadlock.

OK. Not sure of the best way to make per-thread loggers, but I can figure that out. In the meantime, I'm unifying the per-seq firehose logging to just the firehose collector thread.

**Comment by snarfed** [comment]
Looking good here after consolidating logging to the firehose collector. Going to let this run overnight, then I'll declare mission accomplished and merge it back into atproto-hub.

**Comment by snarfed** [comment]
Damn. Still deadlocking. Different than the running-but-not-logging thing earlier. Here's a pruned thread dump from `faulthandler`, and I've attached a full thread dump. Firehose collector is blocked on acquiring the lock to deliver an event to subscribers, https://github.com/snarfed/arroba/blob/60d25df9f1b89acf8d873324d515d104380d4af8/arroba/firehose.py#L221 , but subscribers are all blocked on their event queues' `get`s, and I don't see anything else that's holding the lock. Current thread says it's garbage collecting, but the deadlock lasted 10-15m with seemingly no progress on the firehose collector, so I highly doubt Python was GCing for that long straight.

```
main?
===
File "python3.12/threading.py", line 1012 in run
File "python3.12/threading.py", line 1075 in _bootstrap_inner
File "python3.12/threading.py", line 1032 in _bootstrap


gunicorn main thread
===
Current thread 0x0000791275328740 (most recent call first):
Garbage-collecting
File "python3.12/selectors.py", line 468 in select
File "gunicorn/workers/gthread.py", line 210 in run
File "gunicorn/workers/base.py", line 143 in init_process
File "gunicorn/workers/gthread.py", line 94 in init_process
File "gunicorn/arbiter.py", line 608 in spawn_worker
File "gunicorn/arbiter.py", line 641 in spawn_workers
File "gunicorn/arbiter.py", line 570 in manage_workers
File "gunicorn/arbiter.py", line 201 in run
File "gunicorn/app/base.py", line 71 in run
File "gunicorn/app/base.py", line 235 in run
File "gunicorn/app/wsgiapp.py", line 66 in run
File "pip/bin/gunicorn", line 8 in <module>


idle gunicorn threads?
===
Thread 0x000079123352d640 (most recent call first):
Thread 0x000079123c433640 (most recent call first):
Thread 0x000079123ee37640 (most recent call first):

File "python3.12/concurrent/futures/thread.py", line 90 in _worker
File "python3.12/threading.py", line 1012 in run
File "python3.12/threading.py", line 1075 in _bootstrap_inner
File "python3.12/threading.py", line 1032 in _bootstrap


firehose collector
===
Thread 0x000079125d7fe640 (most recent call first):
File "arroba/firehose.py", line 203 in collect


lexrpc flask_server subscriber timeout iterators
===
Thread 0x000079123bc32640 (most recent call first):
Thread 0x000079123d534640 (most recent call first):
Thread 0x0000791240e3b640 (most recent call first):
Thread 0x000079123fe39640 (most recent call first):
Thread 0x000079123dd35640 (most recent call first):

File "python3.12/threading.py", line 359 in wait
File "python3.12/queue.py", line 180 in get
File "iterators/timeout_iterator.py", line 69 in __next__
File "lexrpc/flask_server.py", line 160 in handle
File "lexrpc/flask_server.py", line 218 in track_subscriber
File "flask_sock/__init__.py", line 62 in websocket_route
File "flask/app.py", line 902 in dispatch_request
File "flask/app.py", line 917 in full_dispatch_request
File "flask/app.py", line 1511 in wsgi_app
File "oauth_dropins/webutil/flask_util.py", line 216 in wrapper
File "flask/app.py", line 1536 in __call__
File "gunicorn/workers/gthread.py", line 333 in handle_request
File "gunicorn/workers/gthread.py", line 281 in handle
File "python3.12/concurrent/futures/thread.py", line 59 in run
File "python3.12/concurrent/futures/thread.py", line 93 in _worker
File "python3.12/threading.py", line 1012 in run
File "python3.12/threading.py", line 1075 in _bootstrap_inner
File "python3.12/threading.py", line 1032 in _bootstrap


subscribers blocking on new events?
===
Thread 0x000079125dfff640 (most recent call first):
Thread 0x000079125f7fe640 (most recent call first):
Thread 0x0000791247fff640 (most recent call first):

File "python3.12/threading.py", line 355 in wait
File "python3.12/queue.py", line 171 in get
File "google/cloud/logging_v2/handlers/transports/background_thread.py", line 68 in _get_many
File "google/cloud/logging_v2/handlers/transports/background_thread.py", line 138 in _thread_main
```

[thread_dump.txt](https://github.com/user-attachments/files/20176096/thread_dump.txt)

**Comment by snarfed** [comment]
Made a few tweaks ^ and added fine grained logging to all lock handling, deploying now, will see.

**Comment by snarfed** [comment]
Still up and serving, 17h later. 292c866 may have done the trick.

**Comment by snarfed** [comment]
Need to do #56 though.

**Comment by snarfed** [comment]
^ done, and merged back into atproto-hub.
